RIOT_PLAYERS = [
    "Megawatt#NA1",
    "JKLgoat#1557",
    "Lord Mountain#yama",
    "Zane#6961",
    "Jushie#NA1",
    "PufferfishLegend#621",
    "bakudeku#qed",
    "JackeyLoveN1yyds#NA1",
    "underworldvisito#NA1",
    "Ken#Smoke",
    "lost in sauce#8888",
    "たくとくたっく#NA1",
    "小幸運#stain",
    "lilac#huaa",
    "JetCracker#NA1",
    "NightingG4le#MPL",
    "theory#tea",
    "Zadeon#悪因悪果",
    "RewJaMaiYoong#NA1",
    "hyunah#jelly",
    "Devvvvvvv#Dev",
    "鍥而不捨#Fear",
    "原神职业哥#99999",
    "IcyDraggy#520",
    "Trispy#3104",
    "FrostyTheSnowman#9865",
    "Chad Te Employee#NA1",
    "Sephere#001",
    "DreadEye#NA2",
    "SakuraMochii#0w0",
    "MoBamla#NA1",
    "tokgii#meow",
    "epitøme#NA1",
    "BizzareMagician#NA1",
    "apeng#9150",
    "carb#10000",
    "Naga1736#NA1",
    "IXX#Meow",
    "biGmicahlE#NA1",
    "Serein#wnter"
]